### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by franfcunha** [almarklein/pyelastix#4] opened 2017-05-03 14:44 UTC
Hi,

How can i directly specify on my python script the path to the output directoy when calling register method? It is giving me the error regarding the inexistance of result.0.mhd file...

Thanks

**Comment by cancan101** [comment] 2018-05-05 00:25
duplicate of: https://github.com/almarklein/pyelastix/issues/1

**Closed as completed** 2019-09-04 17:20 UTC
